FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
COPY tsconfig.json ./
COPY apps/frontend/package*.json ./apps/frontend/
COPY apps/frontend/tsconfig*.json ./apps/frontend/

RUN npm ci --workspaces --if-present

COPY apps/frontend ./apps/frontend
COPY apps/frontend/docker-entrypoint.sh ./apps/frontend/

EXPOSE 5173

WORKDIR /app

RUN chmod +x apps/frontend/docker-entrypoint.sh

ENTRYPOINT ["/app/apps/frontend/docker-entrypoint.sh"]

